# Use Docker-based container (instead of OpenVZ)
sudo: false
language: scala
dist: trusty

scala:
  - "2.12.6"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

jdk: openjdk8

script:
  - git config core.whitespace fix,-indent-with-non-tab,trailing-space,cr-at-eol
  - git show --oneline --check
  - sbt ++$TRAVIS_SCALA_VERSION test

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
